name = "axstore"
main = "worker.js"
account_id = "2be8757c27accc0e32b2e7b191dab316"
workers_dev = true
compatibility_date = "2024-01-01"

kv_namespaces = [
  { binding = "axstore_data", id = "672959a6c9724465a3110f1a64a62c36" }
]

[assets]
binding = "ASSETS"
directory = "public"
